### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by akkaweb** [dereuromark/cakephp-ratings#3]
Hello,

I had added your plugin to an application I am developing and although I tested it briefly to ensure it did not cause any issue, I ended up leaving it for later to fully integrate it into my application. Later down the road though, I started having an issue deleting entries, which was causing the following error: `array_merge(): Argument #2 is not an array`.

I commented out `$this->addBehavior('Ratings.Ratable');` and since the issue continued, I assumed all was OK with it. However, I failed to noticed that the Behavior was still being loaded because I had also added it as a component, `Ratings.Ratings`. Since, I had not caught on to that right away, I thought the issue was being caused by a bug within CakePHP. So I posted on StackOverflow to find some help and you can see details of it and the workaround provided by `ndm`(http://stackoverflow.com/users/1392379/ndm) here:

http://stackoverflow.com/questions/34029445/cakephp-3-array-merge-argument-2-is-not-an-array/34034002#34034002

Please let me know if you think I made a mistake in my setup(missing something) or if there is a fix you can permanently add to this plugin. The workaround fixed the error and I will push ahead with the setup and if I find anymore issues, I will report.

Thanks for a great plugin and I am looking forward to have it setup with my application.

Andre S.

**Comment by dereuromark** [comment]
Is there any stack trace? The error itself is not saying much.

**Comment by dereuromark** [comment]
I read the SO post.
Should be fixed with https://github.com/dereuromark/cakephp-ratings/commit/6bad9442a4f5f8c5779554edcc0cd4a14879699a

**Comment by akkaweb** [comment]
I can confirm it now works. Thanks for the fix!
