### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by dwesolowski** [dereuromark/cakephp-ratings#7]
In your quick start you defined 3 fields

"rating"
"ratung_sum"
"ratung_count"

Are the last 2 spelled right or should they be rating_sum, rating_count?

**Comment by dereuromark** [comment]
Those are typos.

**Comment by dereuromark** [comment]
Fixed in https://github.com/dereuromark/cakephp-ratings/commit/7bf088707de9e370dcf25a07495946257c05a015
